export const CHESS_TYPES = {
  BLACK: 'BLACK',
  WHITE: 'WHITE',
  EMPTY: 'EMPTY',
};

export const DIRECTIONS = {
  HORIZONTAL: 'HORIZONTAL',
  VERTICAL: 'VERTICAL',
  DIAGONAL_TOPLEFT_BOTTOMRIGHT: 'DIAGONAL_TOPLEFT_BOTTOMRIGHT',
  DIAGONAL_TOPRIGHT_BOTTOMLEFT: 'DIAGONAL_TOPRIGHT_BOTTOMLEFT',
};
